version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./instance:/app/instance  # Persist database
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
